language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t warrendreader/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true warrendreader/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react-tutorial'
  env: 'dockerreacttutorial-env'
  bucket_name: 'elasticbeanstalk-us-east-1-750211650059'
  bucket_path: 'docker-react-tutorial'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
